In [6]:
distance = 10000
max_distance = 0
max_test = max([min([5000, distance]), max_distance])
print(max_test)

5000


In [9]:
array = [0]*360
print(array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [14]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.reshape


print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:

x = np.arange(76800).reshape(320, 240)
x

y = x.flatten()

y



array([    0,     1,     2, ..., 76797, 76798, 76799])

In [8]:
import numpy as np
x = np.arange(76800).reshape(320, 240)

slice = x[2,2]
slice



482

In [3]:
texture_data = []
texture_map = {}

for i in range(0, 76800):
    texture_map[f'pixel {i}'] = [
        (82 / 255),
        (82 / 255),
        (82 / 255),
        (255 / 255)]
    texture_data.append(82 / 255)
    texture_data.append(82 / 255)
    texture_data.append(82 / 255)
    texture_data.append(255 / 255)

texture_data
texture_map

{'pixel 0': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 1': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 2': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 3': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 4': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 5': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 6': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 7': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 8': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 9': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 10': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 11': [0.3215686274509804, 0.3215686274509804, 0.3215686274509804, 1.0],
 'pixel 12': [0.3215686274509804, 0.32156862745098