In [6]:
distance = 10000
max_distance = 0
max_test = max([min([5000, distance]), max_distance])
print(max_test)

5000


IndexError: list index out of range

In [9]:
array = [0]*360
print(array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [14]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.reshape


print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:

x = np.arange(76800).reshape(320, 240)
x

y = x.flatten()

y



array([    0,     1,     2, ..., 76797, 76798, 76799])

In [8]:
import numpy as np
x = np.arange(76800).reshape(320, 240)

slice = x[2,2]
slice



482

In [9]:
import numpy as np
scan_data = [0]*360
degrees = np.arange(320 * 240).reshape(320, 240)

degrees

array([[    0,     1,     2, ...,   237,   238,   239],
       [  240,   241,   242, ...,   477,   478,   479],
       [  480,   481,   482, ...,   717,   718,   719],
       ...,
       [76080, 76081, 76082, ..., 76317, 76318, 76319],
       [76320, 76321, 76322, ..., 76557, 76558, 76559],
       [76560, 76561, 76562, ..., 76797, 76798, 76799]])

In [2]:
i = 1 
if i:
    print('OK')

OK


In [14]:
import numpy as np 
import pygame
from rplidar import RPLidar
from math import cos, sin, pi, floor

# Set up pygame and the display
pygame.init()
lcd = pygame.display.set_mode((320,240))
pygame.mouse.set_visible(False)
lcd.fill((0,0,0))
pygame.display.update()

# Setup the RPLidar
PORT_NAME = 'COM4'
lidar = RPLidar(PORT_NAME)
lidar.stop_motor()
input('Go?: ')
scan_data = [0]*360


degrees = np.array(scan_data).reshape(4,90)
max_distance = 0
foo = 0

def process_data(data,foo):
    global max_distance
    lcd.fill((0,0,0))
    
    
    for angle in range(360):
        # if foo == 50:
        #     print(data)
        #     print(len(data))
        
        distance = data[angle]
        if distance > 0:                  # ignore initially ungathered data points
            max_distance = max([min([5000, distance]), max_distance])
            radians = angle * pi / 180.0
            x = distance * cos(radians)
            y = distance * sin(radians)
            point = (160 + int(x / max_distance * 119), 120 + int(y / max_distance * 119))  # (1,2) 
            lcd.set_at(point, pygame.Color(255, 255, 255))
    pygame.display.update()



try:
    for i, scan in enumerate(lidar.iter_scans()):
        for (quality, angle, distance) in scan:
            if angle >= 0 and angle <= 90:
                scan_data[min([359, floor(angle)])] = distance
                degrees[0][min([359, floor(angle)])] = distance
            elif angle > 90 and angle <= 180:
                scan_data[min([359, floor(angle)])] = distance
                degrees[1][min([359, floor(angle) - 90 ])] = distance
            elif angle > 180 and angle <= 270:
                scan_data[min([359, floor(angle)])] = distance
                degrees[2][min([359, floor(angle) - 180])] = distance
            elif angle > 270 and angle <=360:
                scan_data[min([359, floor(angle)])] = distance
                degrees[3][min([359, floor(angle) - 270])] = distance

                
                # if foo == 50:
                #     print(f'Quality: {quality}')
                #     print(f'Angle: {angle}')
                #     print(f'Distance: {distance}')
        foo += 1
        if foo == 50:
            print(degrees)
        process_data(scan_data,foo)


except KeyboardInterrupt:
    print('Stoping.')
lidar.stop()
lidar.disconnect()

RPLidarException: Failed to connect to the sensor due to: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)